spring:
  application:
    name: clock
  datasource:
    url: jdbc:h2:mem:clockdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2-console
